version: 2
updates:
  - package-ecosystem: maven
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: daily
    ignore:
    - dependency-name: "org.flywaydb:flyway-core"
      versions: ["10.x"]
